name: sih_23_audiometer
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.2 <4.0.0"

dependencies:
  audio_streamer: ^4.0.0
  audioplayers: ^5.2.1
  audioplayers_web: ^4.1.0
  cloud_firestore: ^4.13.6
  cupertino_icons: ^1.0.2
  datetime_picker_formfield_new: ^2.1.0
  file_picker: ^6.1.1
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.5.6
  flutter:
    sdk: flutter
  flutter_sound: ^9.2.13
  flutter_test:
    sdk: flutter
  fluttertoast: ^8.2.4
  font_awesome_flutter: ^10.6.0
  google_fonts: ^6.1.0
  google_sign_in: ^6.2.1
  headset_connection_event: ^3.1.0
  volume_watcher: ^2.0.1
  perfect_volume_control: ^1.0.5
  noise_meter: ^5.0.2
  permission_handler: ^11.1.0
  syncfusion_flutter_charts: ^23.2.7
  url_launcher: ^6.2.2
  velocity_x: ^4.1.2

dev_dependencies:
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets\audio\tone.mp3
    - assets\images\abhi.png
    - assets\images\login.jpg
    - assets\images\signup.png
    - assets\images\bluetooth.png
    - assets\images\headphone.png
    - assets\images\eduapp_student_login.jpg
    - assets\images\admin.png
    - assets\images\leftear.png
    - assets\images\rightear.png
    - assets\images\eduapp_student_login.jpg
    - assets\audio\250hz.mp3
    - assets\audio\500hz.mp3
    - assets\audio\1000hz.mp3
    - assets\audio\2000hz.mp3
    - assets\audio\4000hz.mp3
    - assets\audio\8000hz.mp3
    - assets\images\bluecrossgraph.png
    - assets\images\baground.jpg
    - assets\images\admin.png
